  { config, pkgs, noctalia, username, ... }:
 
  {
     imports = [ noctalia.homeModules.default ];

     home = {
       username = username;
       homeDirectory = "/home/${username}";
       stateVersion = "26.05";
packages = with pkgs; [
          kitty
          fish
          firefox
          tree
          neovim
          git
          opencode
          pulseaudio
          starship
          wl-clipboard # nvim system clipboard (wl-copy/wl-paste)
          lazygit # <leader>gg in LazyVim
          ripgrep # telescope live-grep
          fd # telescope file finding
          gcc # tree-sitter parser + avante build
          gnumake # avante build step
          bibata-cursors # Bibata-Modern-Classic (black) cursor theme
          papirus-icon-theme # folder colors follow Noctalia accent via theme-sync.sh
          papirus-folders # recolor tool for the above
          nautilus # file manager
          gvfs # trash, network, device mounting for nautilus
          unzip # mason package installs
          gh # github cli
        ];

        sessionVariables = {
          XCURSOR_THEME = "Bibata-Modern-Classic";
          XCURSOR_SIZE = "24";
        };

        file.".config/niri/config.kdl".source = ./niri-config.kdl;
        file.".config/noctalia/config.toml".source = ./noctalia-config.toml;
        file.".config/fish/config.fish".source = ./fish-config.fish;
        file.".config/kitty/kitty.conf".source = ./kitty.conf;
        file.".config/nvim".source = ./nvim;
      };

      # GTK apps (nautilus, firefox) pick the cursor from gsettings, not env vars.
      dconf.settings."org/gnome/desktop/interface" = {
        cursor-theme = "Bibata-Modern-Classic";
        cursor-size = 24;
        color-scheme = "prefer-dark";
        gtk-theme = "Adwaita-dark";
        icon-theme = "Papirus-Dark";
        font-name = "DejaVu Sans 11";
      };

      # System-wide font defaults: standard sans for app UIs; kitty keeps
      # its monospace look via fontconfig's monospace default.
      fonts.fontconfig.defaultFonts.sansSerif = [ "DejaVu Sans" ];
      fonts.fontconfig.defaultFonts.monospace = [ "DejaVu Sans Mono" ];

      # Smaller icons in Nautilus grid view.
      dconf.settings."org/gnome/nautilus/preferences" = {
        default-zoom-level = "small";
      };

      # Noctalia themes GTK apps via CSS only; it never writes settings.ini.
      # Firefox's System Theme reads the GTK theme name / dark flag instead,
      # so declare them here or it renders light.
      xdg.configFile."gtk-3.0/settings.ini".text = ''
        [Settings]
        gtk-theme-name=Adwaita-dark
        gtk-application-prefer-dark-theme=true
      '';
      xdg.configFile."gtk-4.0/settings.ini".text = ''
        [Settings]
        gtk-theme-name=Adwaita-dark
        gtk-application-prefer-dark-theme=true
      '';

      # Firefox has no Noctalia template; sync its UI colors by converting
      # Noctalia's generated GTK palette into userChrome.css for every profile.
      # Same script emits an opencode TUI theme from the same palette.
      xdg.configFile."noctalia/theme-sync.sh" = {
        executable = true;
        text = ''
          #!/usr/bin/env bash
          # Regenerate app themes from Noctalia's generated GTK palette.
          set -eu
          CSS="$HOME/.config/gtk-4.0/noctalia.css"
          [ -f "$CSS" ] || exit 0
          get() { sed -n "s/^@define-color[[:space:]]*$1[[:space:]]*\(#[0-9a-fA-F]*\).*/\1/p" "$CSS" | head -1; }
          BG=$(get window_bg_color)
          FG=$(get window_fg_color)
          ACC=$(get accent_color)
          CARD=$(get card_bg_color)
          POP=$(get popover_bg_color)
          SIDEBAR=$(get sidebar_bg_color)
          MUT=$(get theme_unfocused_fg_color)
          BORD=$(get sidebar_border_color)
          RED=$(get destructive_bg_color)
          SEL=$(get theme_selected_bg_color)
          : "''${BG:=#1b1b1f}" "''${FG:=#e3e3e8}" "''${ACC:=#8ab4ff}"
          : "''${CARD:=#24242c}" "''${POP:=#2a2a33}" "''${SIDEBAR:=#202028}"
          : "''${MUT:=#8b8d98}" "''${BORD:=#2e3037}" "''${RED:=#ffb4ab}" "''${SEL:=$ACC}"

          # --- Firefox userChrome.css ---
          CHROME="/* Generated by noctalia-theme-sync.sh - do not edit */
          :root {
            --lwt-text-color: $FG !important;
            --toolbar-color: $FG !important;
            --tab-selected-textcolor: $FG !important;
            --arrowpanel-background: $POP !important;
            --arrowpanel-color: $FG !important;
            --panel-color: $FG !important;
            --autocomplete-popup-color: $FG !important;
            --sidebar-text-color: $FG !important;
          }
          /* Paint chrome elements directly: --lwt-* background vars are
             ignored unless a lightweight theme is active. */
          #navigator-toolbox, #TabsToolbar, #nav-bar { background-color: $BG !important; }
          #PersonalToolbar { background-color: $CARD !important; }
          .tab-background[selected]:not([multiselected]) {
            background-color: $POP !important;
          }
          .tabbrowser-tab:hover > .tab-stack > .tab-background:not([selected]) {
            background-color: color-mix(in srgb, $ACC 14%, transparent) !important;
          }
          #sidebar-box, .browser-sidebar2 { background-color: $SIDEBAR !important; }
          findbar { background-color: $CARD !important; }
          menupopup { background-color: $POP !important; }
          menupopup > menu:hover,
          menupopup > menuitem:hover {
            background: color-mix(in srgb, $ACC 22%, transparent) !important;
          }"
          # Find every registered profile via profiles.ini (Firefox may live
          # under ~/.config/mozilla or the legacy ~/.mozilla).
          for ini in "$HOME/.config/mozilla/firefox/profiles.ini" "$HOME/.mozilla/firefox/profiles.ini"; do
            [ -f "$ini" ] || continue
            root=$(dirname "$ini")
            while IFS= read -r p; do
              [ -n "$p" ] || continue
              case "$p" in
                /*) prof="$p" ;;
                *) prof="$root/$p" ;;
              esac
              [ -d "$prof" ] || continue
              mkdir -p "$prof/chrome"
              printf '%s\n' "$CHROME" > "$prof/chrome/userChrome.css"
            done < <(grep '^Path=' "$ini" | cut -d= -f2-)
          done

          # --- opencode TUI theme ---
          mkdir -p "$HOME/.config/opencode/themes"
          cat > "$HOME/.config/opencode/themes/noctalia.json" <<EOF
          {
            "\$schema": "https://opencode.ai/theme.json",
            "defs": {
              "bg": "$BG", "panel": "$CARD", "elem": "$POP", "fg": "$FG",
              "muted": "$MUT", "accent": "$ACC", "border": "$BORD",
              "sel": "$SEL", "red": "$RED", "green": "#9ece8f"
            },
            "theme": {
              "primary": { "dark": "accent", "light": "accent" },
              "secondary": { "dark": "sel", "light": "sel" },
              "accent": { "dark": "accent", "light": "accent" },
              "error": { "dark": "red", "light": "red" },
              "warning": { "dark": "red", "light": "red" },
              "info": { "dark": "accent", "light": "accent" },
              "success": { "dark": "green", "light": "green" },
              "text": { "dark": "fg", "light": "fg" },
              "textMuted": { "dark": "muted", "light": "muted" },
              "background": { "dark": "bg", "light": "bg" },
              "backgroundPanel": { "dark": "panel", "light": "panel" },
              "backgroundElement": { "dark": "elem", "light": "elem" },
              "border": { "dark": "border", "light": "border" },
              "borderActive": { "dark": "accent", "light": "accent" },
              "borderSubtle": { "dark": "border", "light": "border" },
              "diffAdded": { "dark": "green", "light": "green" },
              "diffRemoved": { "dark": "red", "light": "red" },
              "diffContext": { "dark": "muted", "light": "muted" },
              "diffHunkHeader": { "dark": "muted", "light": "muted" },
              "diffHighlightAdded": { "dark": "green", "light": "green" },
              "diffHighlightRemoved": { "dark": "red", "light": "red" },
              "diffAddedBg": { "dark": "panel", "light": "panel" },
              "diffRemovedBg": { "dark": "panel", "light": "panel" },
              "diffContextBg": { "dark": "bg", "light": "bg" },
              "diffLineNumber": { "dark": "border", "light": "border" },
              "markdownText": { "dark": "fg", "light": "fg" },
              "markdownHeading": { "dark": "accent", "light": "accent" },
              "markdownLink": { "dark": "sel", "light": "sel" },
              "markdownLinkText": { "dark": "accent", "light": "accent" },
              "markdownCode": { "dark": "green", "light": "green" },
              "markdownBlockQuote": { "dark": "muted", "light": "muted" },
              "markdownEmph": { "dark": "red", "light": "red" },
              "markdownStrong": { "dark": "fg", "light": "fg" },
              "syntaxComment": { "dark": "muted", "light": "muted" },
              "syntaxKeyword": { "dark": "sel", "light": "sel" },
              "syntaxFunction": { "dark": "accent", "light": "accent" },
              "syntaxVariable": { "dark": "fg", "light": "fg" },
              "syntaxString": { "dark": "green", "light": "green" },
              "syntaxNumber": { "dark": "red", "light": "red" },
              "syntaxType": { "dark": "sel", "light": "sel" },
              "syntaxOperator": { "dark": "sel", "light": "sel" },
              "syntaxPunctuation": { "dark": "muted", "light": "muted" }
            }
          }
          EOF

          # --- Papirus folder color follows the accent hue ---
          # Runs against a writable copy in ~/.local/share/icons (the store
          # copy is read-only); skips work when the color is unchanged.
          if command -v papirus-folders >/dev/null 2>&1; then
            H=$(printf '%s' "$ACC" | awk '{
              r = strtonum("0x" substr($0, 2, 2))
              g = strtonum("0x" substr($0, 4, 2))
              b = strtonum("0x" substr($0, 6, 2))
              mx = r > g ? (r > b ? r : b) : (g > b ? g : b)
              mn = r < g ? (r < b ? r : b) : (g < b ? g : b)
              d = mx - mn
              if (d == 0) { print 220; exit }
              h = (mx == r) ? (g - b) / d : ((mx == g) ? (b - r) / d + 2 : (r - g) / d + 4)
              print (h * 60 + 360) % 360
            }' 2>/dev/null || echo 220)
            H=$(printf '%.0f' "''${H:-220}" 2>/dev/null || echo 220)
            COLOR=blue
            if   [ "$H" -lt 15 ] || [ "$H" -ge 345 ]; then COLOR=red
            elif [ "$H" -lt 45 ];  then COLOR=orange
            elif [ "$H" -lt 70 ];  then COLOR=yellow
            elif [ "$H" -lt 160 ]; then COLOR=green
            elif [ "$H" -lt 200 ]; then COLOR=cyan
            elif [ "$H" -lt 255 ]; then COLOR=blue
            elif [ "$H" -lt 285 ]; then COLOR=indigo
            elif [ "$H" -lt 320 ]; then COLOR=violet
            else                        COLOR=magenta
            fi
            STATE="$HOME/.cache/noctalia-papirus-color"
            DST="$HOME/.local/share/icons/Papirus-Dark"
            SRC="/etc/profiles/per-user/$(id -un)/share/icons/Papirus-Dark"
            if [ ! -d "$SRC" ]; then
              PF=$(command -v papirus-folders)
              [ -n "$PF" ] && SRC="$(dirname "$(dirname "$PF")")/share/icons/Papirus-Dark"
            fi
            if [ -d "$SRC" ] && [ "$COLOR" != "$(cat "$STATE" 2>/dev/null || true)" ]; then
              if [ ! -d "$DST" ]; then
                mkdir -p "$HOME/.local/share/icons"
                rm -rf "$DST.tmp"
                cp -r "$SRC" "$DST.tmp" && mv "$DST.tmp" "$DST"
              fi
              if papirus-folders -C --theme Papirus-Dark --color "$COLOR" >/dev/null 2>&1; then
                command -v gtk-update-icon-cache >/dev/null 2>&1 && gtk-update-icon-cache -f "$DST" >/dev/null 2>&1 || true
                printf '%s' "$COLOR" > "$STATE"
              fi
            fi
          fi
        '';
      };
      systemd.user.services.noctalia-theme-sync = {
        Unit.Description = "Sync app themes (Firefox, opencode) with Noctalia";
        Service = {
          Type = "oneshot";
          ExecStart = "%h/.config/noctalia/theme-sync.sh";
        };
      };
      systemd.user.paths.noctalia-theme-sync = {
        Unit.Description = "Watch Noctalia GTK palette for changes";
        Path.PathChanged = [ "%h/.config/gtk-4.0/noctalia.css" ];
        Install.WantedBy = [ "default.target" ];
      };

      # Use the generated Noctalia theme in opencode's TUI.
      xdg.configFile."opencode/tui.json".text = ''
        {
          "$schema": "https://opencode.ai/tui.json",
          "theme": "noctalia"
        }
      '';

      # Arch logo for the Noctalia bar launcher button.
      xdg.configFile."noctalia/arch-logo.svg".source = ./assets/arch-logo.svg;

    xdg.configFile."wireplumber/wireplumber.conf.d/50-bluez-a2dp.conf".text = ''
      monitor.bluez.rules = [
        {
          matches = [
            {
              device.name = "~bluez_card.F4_4E_FC_EB_62_87$"
            }
          ]
          actions = {
            update-props = {
              bluez5.profiles = [ a2dp_sink ]
            }
          }
        }
      ]
    '';

    programs = {
      bash = {
        enable = true;
        shellAliases = {
          btw = "echo i use arch btw";
        };
      };
      noctalia = {
        enable = true;
      };
    };
  }  
