  { config, pkgs, noctalia, username, ... }:
 
  {
     imports = [ noctalia.homeModules.default ];

     home = {
       username = username;
       homeDirectory = "/home/${username}";
       stateVersion = "26.05";
packages = with pkgs; [
          kitty
          fish
          firefox
          tree
          neovim
          git
          opencode
          pulseaudio
          starship
          wl-clipboard # nvim system clipboard (wl-copy/wl-paste)
          lazygit # <leader>gg in LazyVim
          ripgrep # telescope live-grep
          fd # telescope file finding
          gcc # tree-sitter parser + avante build
          gnumake # avante build step
          bibata-cursors # Bibata-Modern-Classic (black) cursor theme
          nautilus # file manager
          gvfs # trash, network, device mounting for nautilus
          unzip # mason package installs
          gh # github cli
        ];

        sessionVariables = {
          XCURSOR_THEME = "Bibata-Modern-Classic";
          XCURSOR_SIZE = "24";
        };

        file.".config/niri/config.kdl".source = ./niri-config.kdl;
        file.".config/noctalia/config.toml".source = ./noctalia-config.toml;
        file.".config/fish/config.fish".source = ./fish-config.fish;
        file.".config/kitty/kitty.conf".source = ./kitty.conf;
        file.".config/nvim".source = ./nvim;
      };

      # GTK apps (nautilus, firefox) pick the cursor from gsettings, not env vars.
      dconf.settings."org/gnome/desktop/interface" = {
        cursor-theme = "Bibata-Modern-Classic";
        cursor-size = 24;
        color-scheme = "prefer-dark";
        gtk-theme = "Adwaita-dark";
      };

      # Noctalia themes GTK apps via CSS only; it never writes settings.ini.
      # Firefox's System Theme reads the GTK theme name / dark flag instead,
      # so declare them here or it renders light.
      xdg.configFile."gtk-3.0/settings.ini".text = ''
        [Settings]
        gtk-theme-name=Adwaita-dark
        gtk-application-prefer-dark-theme=true
      '';
      xdg.configFile."gtk-4.0/settings.ini".text = ''
        [Settings]
        gtk-theme-name=Adwaita-dark
        gtk-application-prefer-dark-theme=true
      '';

      # Firefox has no Noctalia template; sync its UI colors by converting
      # Noctalia's generated GTK palette into userChrome.css for every profile.
      xdg.configFile."noctalia/firefox-theme.sh" = {
        executable = true;
        text = ''
          #!/usr/bin/env bash
          # Regenerate Firefox userChrome.css from Noctalia's GTK palette.
          set -eu
          CSS="$HOME/.config/gtk-4.0/noctalia.css"
          [ -f "$CSS" ] || exit 0
          get() { sed -n "s/^@define-color[[:space:]]*$1[[:space:]]*\(#[0-9a-fA-F]*\).*/\1/p" "$CSS" | head -1; }
          BG=$(get window_bg_color)
          FG=$(get window_fg_color)
          ACC=$(get accent_color)
          CARD=$(get card_bg_color)
          POP=$(get popover_bg_color)
          SIDEBAR=$(get sidebar_bg_color)
          : "''${BG:=#1b1b1f}" "''${FG:=#e3e3e8}" "''${ACC:=#8ab4ff}"
          : "''${CARD:=#24242c}" "''${POP:=#2a2a33}" "''${SIDEBAR:=#202028}"
          CHROME="/* Generated by noctalia-firefox-theme.sh - do not edit */
          :root {
            --lwt-accent-color: $BG !important;
            --lwt-text-color: $FG !important;
            --toolbar-bgcolor: $CARD !important;
            --toolbar-color: $FG !important;
            --chrome-content-separator-color: $CARD !important;
            --tab-selected-bgcolor: $POP !important;
            --tab-selected-textcolor: $FG !important;
            --urlbar-box-bgcolor: $CARD !important;
            --arrowpanel-background: $POP !important;
            --arrowpanel-color: $FG !important;
            --panel-background: $POP !important;
            --panel-color: $FG !important;
            --autocomplete-popup-background: $POP !important;
            --autocomplete-popup-color: $FG !important;
            --sidebar-background-color: $SIDEBAR !important;
            --sidebar-text-color: $FG !important;
          }
          menupopup > menu:hover,
          menupopup > menuitem:hover {
            background: color-mix(in srgb, $ACC 22%, transparent) !important;
          }"
          # Find every registered profile via profiles.ini (Firefox may live
          # under ~/.config/mozilla or the legacy ~/.mozilla).
          for ini in "$HOME/.config/mozilla/firefox/profiles.ini" "$HOME/.mozilla/firefox/profiles.ini"; do
            [ -f "$ini" ] || continue
            root=$(dirname "$ini")
            while IFS= read -r p; do
              [ -n "$p" ] || continue
              case "$p" in
                /*) prof="$p" ;;
                *) prof="$root/$p" ;;
              esac
              [ -d "$prof" ] || continue
              mkdir -p "$prof/chrome"
              printf '%s\n' "$CHROME" > "$prof/chrome/userChrome.css"
            done < <(grep '^Path=' "$ini" | cut -d= -f2-)
          done
        '';
      };
      systemd.user.services.noctalia-firefox-theme = {
        Unit.Description = "Sync Firefox UI colors with Noctalia";
        Service = {
          Type = "oneshot";
          ExecStart = "%h/.config/noctalia/firefox-theme.sh";
        };
      };
      systemd.user.paths.noctalia-firefox-theme = {
        Unit.Description = "Watch Noctalia GTK palette for changes";
        Path.PathChanged = [ "%h/.config/gtk-4.0/noctalia.css" ];
        Install.WantedBy = [ "default.target" ];
      };

    xdg.configFile."wireplumber/wireplumber.conf.d/50-bluez-a2dp.conf".text = ''
      monitor.bluez.rules = [
        {
          matches = [
            {
              device.name = "~bluez_card.F4_4E_FC_EB_62_87$"
            }
          ]
          actions = {
            update-props = {
              bluez5.profiles = [ a2dp_sink ]
            }
          }
        }
      ]
    '';

    programs = {
      bash = {
        enable = true;
        shellAliases = {
          btw = "echo i use arch btw";
        };
      };
      noctalia = {
        enable = true;
      };
    };
  }  
